CREATE TABLE activity_logs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id      BIGINT,
    action        VARCHAR(32)  NOT NULL,
    target_type   VARCHAR(16),
    target_id     BIGINT,
    detail        VARCHAR(255),
    ip_address    VARCHAR(64),
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_activity_actor FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE INDEX idx_activity_logs_created_at ON activity_logs(created_at DESC);
CREATE INDEX idx_activity_logs_actor      ON activity_logs(actor_id);
CREATE INDEX idx_activity_logs_action     ON activity_logs(action);
