CREATE TABLE code_groups (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code  VARCHAR(50)  NOT NULL UNIQUE,
    group_name  VARCHAR(200) NOT NULL,
    description TEXT
);

CREATE TABLE codes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT       NOT NULL,
    code_value  VARCHAR(50)  NOT NULL,
    code_label  VARCHAR(200) NOT NULL,
    sort_order  INTEGER      DEFAULT 0,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_codes_group FOREIGN KEY (group_id) REFERENCES code_groups(id),
    CONSTRAINT uq_codes_group_value UNIQUE (group_id, code_value)
);

INSERT INTO code_groups (group_code, group_name, description) VALUES
('REQUEST_STATUS', 'Request Status', 'Status codes for ATOM/CPSR requests'),
('REQUEST_PRIORITY', 'Request Priority', 'Priority levels for requests'),
('REQUEST_TYPE', 'Request Type', 'Type of request (ATOM/CPSR)'),
('DEPARTMENT', 'Department', 'Department codes');

INSERT INTO codes (group_id, code_value, code_label, sort_order) VALUES
(1, 'DRAFT', 'Draft', 1),
(1, 'SUBMITTED', 'Submitted', 2),
(1, 'UNDER_REVIEW', 'Under Review', 3),
(1, 'APPROVED', 'Approved', 4),
(1, 'REJECTED', 'Rejected', 5),
(1, 'CANCELLED', 'Cancelled', 6),
(2, 'LOW', 'Low', 1),
(2, 'MEDIUM', 'Medium', 2),
(2, 'HIGH', 'High', 3),
(2, 'URGENT', 'Urgent', 4),
(3, 'ATOM', 'ATOM', 1),
(3, 'CPSR', 'CPSR', 2);
