CREATE TABLE IF NOT EXISTS atom_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    evaluation_result TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_atom_requests_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS cpsr_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL REFERENCES users(id),
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    evaluation_result TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_cpsr_requests_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS request_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atom_request_id BIGINT REFERENCES atom_requests(id) ON DELETE CASCADE,
    cpsr_request_id BIGINT REFERENCES cpsr_requests(id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL REFERENCES users(id),
    body TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_request_comments_one_request CHECK (
        (atom_request_id IS NOT NULL AND cpsr_request_id IS NULL)
        OR (atom_request_id IS NULL AND cpsr_request_id IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS request_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_type VARCHAR(16) NOT NULL,
    request_id BIGINT NOT NULL,
    actor_id BIGINT NOT NULL REFERENCES users(id),
    from_status VARCHAR(32),
    to_status VARCHAR(32) NOT NULL,
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_request_history_type CHECK (request_type IN ('ATOM', 'CPSR'))
);

CREATE INDEX IF NOT EXISTS ix_atom_requests_owner_status ON atom_requests(owner_id, status);
CREATE INDEX IF NOT EXISTS ix_cpsr_requests_owner_status ON cpsr_requests(owner_id, status);
CREATE INDEX IF NOT EXISTS ix_request_comments_atom ON request_comments(atom_request_id);
CREATE INDEX IF NOT EXISTS ix_request_comments_cpsr ON request_comments(cpsr_request_id);
CREATE INDEX IF NOT EXISTS ix_request_history_request ON request_history(request_type, request_id, created_at);
