CREATE TABLE jwt_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti VARCHAR(36) NOT NULL,
    username VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_jwt_sessions_jti UNIQUE (jti)
);

CREATE INDEX idx_jwt_sessions_username ON jwt_sessions (username);
