CREATE TABLE IF NOT EXISTS attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    atom_request_id BIGINT REFERENCES atom_requests(id) ON DELETE CASCADE,
    cpsr_request_id BIGINT REFERENCES cpsr_requests(id) ON DELETE CASCADE,
    uploaded_by BIGINT NOT NULL REFERENCES users(id),
    original_filename VARCHAR(500) NOT NULL,
    stored_filename VARCHAR(500) NOT NULL,
    content_type VARCHAR(255) NOT NULL,
    size BIGINT NOT NULL,
    checksum VARCHAR(64) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_attachments_one_request CHECK (
        (atom_request_id IS NOT NULL AND cpsr_request_id IS NULL)
        OR (atom_request_id IS NULL AND cpsr_request_id IS NOT NULL)
    )
);

CREATE INDEX IF NOT EXISTS ix_attachments_atom ON attachments(atom_request_id);
CREATE INDEX IF NOT EXISTS ix_attachments_cpsr ON attachments(cpsr_request_id);
CREATE INDEX IF NOT EXISTS ix_attachments_uploaded_by ON attachments(uploaded_by);
